### ISSUE TITLE
Where conditions?

### ISSUE THREAD

**Issue by acao** [fullcube/loopback-ds-computed-mixin#2]
Maybe this isn't possible, but is there a way to possibly accomplish filtering by where conditions on computed properties? Or does that defeat the purpose? I'd imagine if that is a requirement then you need to actually use the database?

**Comment by beeman** [comment]
Can you explain a use case when you'd need something like that? 

The computed properties are implemented on the `loaded` observer, so the computed properties will only be added to the data that comes from the DB, which is possible already filtered.

If you need to filter data inside the method that is used to compute the property, [loopback-filters](https://github.com/strongloop/loopback-filters) might be useful.

**Comment by acao** [comment]
Indeed - the loaded observer is what i was using manually, but I'll be switching to this component.

I have a computed property that counts the quantity of models related to a specific model. Think of an article and it having a dynamic commentCount property.

Then, imagine that you want to return an array of articles that have a commentCount greater than 0, or  also an array of articles sorted by commentCount.

So yeah, this will have to be a database stored property. I'm guessing I can develop some of my own mixins to make this happen more readily, in a fashion similar to this computed mixin. Or maybe I should just write defaultFunctions.

**Comment by kbrandwijk** [comment]
I have implemented this in #8. 
It preserves the field filter using the `access` observer and checks it in the `loaded` observer.
